# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@types/bun@1.1.14" = fetchurl {
    url = "https://registry.npmjs.org/@types/bun/-/bun-1.1.14.tgz";
    hash = "sha512-opVYiFGtO2af0dnWBdZWlioLBoxSdDO5qokaazLhq8XQtGZbY4pY3/JxY8Zdf/hEwGubbp7ErZXoN1+h2yesxA==";
  };
  "@types/node@20.12.14" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-20.12.14.tgz";
    hash = "sha512-scnD59RpYD91xngrQQLGkE+6UrHUPzeKZWhhjBSa3HSkwjbQc38+q3RoIVEwxQGRw3M+j5hpNAM+lgV3cVormg==";
  };
  "@types/ws@8.5.14" = fetchurl {
    url = "https://registry.npmjs.org/@types/ws/-/ws-8.5.14.tgz";
    hash = "sha512-bd/YFLW+URhBzMXurx7lWByOu+xzU9+kb3RboOteXYDfW+tr+JZa99OyNmPINEGB/ahzKrEuc8rcv4gnpJmxTw==";
  };
  "bun-types@1.1.34" = fetchurl {
    url = "https://registry.npmjs.org/bun-types/-/bun-types-1.1.34.tgz";
    hash = "sha512-br5QygTEL/TwB4uQOb96Ky22j4Gq2WxWH/8Oqv20fk5HagwKXo/akB+LiYgSfzexCt6kkcUaVm+bKiPl71xPvw==";
  };
  "bun-types@1.1.37" = fetchurl {
    url = "https://registry.npmjs.org/bun-types/-/bun-types-1.1.37.tgz";
    hash = "sha512-C65lv6eBr3LPJWFZ2gswyrGZ82ljnH8flVE03xeXxKhi2ZGtFiO4isRKTKnitbSqtRAcaqYSR6djt1whI66AbA==";
  };
  "smol-toml@1.3.1" = fetchurl {
    url = "https://registry.npmjs.org/smol-toml/-/smol-toml-1.3.1.tgz";
    hash = "sha512-tEYNll18pPKHroYSmLLrksq233j021G0giwW7P3D24jC54pQ5W5BXMsQ/Mvw1OJCmEYDgY+lrzT+3nNUtoNfXQ==";
  };
  "typescript@5.7.3" = fetchurl {
    url = "https://registry.npmjs.org/typescript/-/typescript-5.7.3.tgz";
    hash = "sha512-84MVSjMEHP+FQRPy3pX9sTVV/INIex71s9TL2Gm5FG/WG1SqXeKyZ0k7/blY/4FdOzI12CBy1vGc4og/eus0fw==";
  };
  "undici-types@5.26.5" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-5.26.5.tgz";
    hash = "sha512-JlCMO+ehdEIKqlFxk6IfVoAUVmgz7cU7zD/h9XZ0qzeosSHmUJVOzSQvvYSYWXkFXC+IfLKSIffhv0sVZup6pA==";
  };
}