[package]
name = "tally-flow"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
readme = "README.md"

[dependencies]
boa_ast.workspace = true
boa_engine.workspace = true
boa_gc.workspace = true
boa_interner.workspace = true
boa_parser.workspace = true
futures-lite.workspace = true
jsonschema.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
